services:
  - type: web
    name: autoreplyx-web
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: VITE_API_URL
        value: https://original-gertie-autoplyx-200c1a3a.koyeb.app/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
